<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  35987 => 'Vivacom',
  35988 => 'M-Tel',
  35989 => 'Telenor',
  359988 => 'bob',
  359999 => 'MAX',
);
